# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xue/OpenCV/Test/onnxc++depth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xue/OpenCV/Test/onnxc++depth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xue/OpenCV/Test/onnxc++depth/CMakeFiles /home/xue/OpenCV/Test/onnxc++depth/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xue/OpenCV/Test/onnxc++depth/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named onnxrun2

# Build rule for target.
onnxrun2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 onnxrun2
.PHONY : onnxrun2

# fast build rule for target.
onnxrun2/fast:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/build
.PHONY : onnxrun2/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/main.cpp.s
.PHONY : main.cpp.s

src/serial_port.o: src/serial_port.cpp.o

.PHONY : src/serial_port.o

# target to build an object file
src/serial_port.cpp.o:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/serial_port.cpp.o
.PHONY : src/serial_port.cpp.o

src/serial_port.i: src/serial_port.cpp.i

.PHONY : src/serial_port.i

# target to preprocess a source file
src/serial_port.cpp.i:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/serial_port.cpp.i
.PHONY : src/serial_port.cpp.i

src/serial_port.s: src/serial_port.cpp.s

.PHONY : src/serial_port.s

# target to generate assembly for a file
src/serial_port.cpp.s:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/serial_port.cpp.s
.PHONY : src/serial_port.cpp.s

src/tower.o: src/tower.cpp.o

.PHONY : src/tower.o

# target to build an object file
src/tower.cpp.o:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/tower.cpp.o
.PHONY : src/tower.cpp.o

src/tower.i: src/tower.cpp.i

.PHONY : src/tower.i

# target to preprocess a source file
src/tower.cpp.i:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/tower.cpp.i
.PHONY : src/tower.cpp.i

src/tower.s: src/tower.cpp.s

.PHONY : src/tower.s

# target to generate assembly for a file
src/tower.cpp.s:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/tower.cpp.s
.PHONY : src/tower.cpp.s

src/yolo.o: src/yolo.cpp.o

.PHONY : src/yolo.o

# target to build an object file
src/yolo.cpp.o:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/yolo.cpp.o
.PHONY : src/yolo.cpp.o

src/yolo.i: src/yolo.cpp.i

.PHONY : src/yolo.i

# target to preprocess a source file
src/yolo.cpp.i:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/yolo.cpp.i
.PHONY : src/yolo.cpp.i

src/yolo.s: src/yolo.cpp.s

.PHONY : src/yolo.s

# target to generate assembly for a file
src/yolo.cpp.s:
	$(MAKE) -f CMakeFiles/onnxrun2.dir/build.make CMakeFiles/onnxrun2.dir/src/yolo.cpp.s
.PHONY : src/yolo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... onnxrun2"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/serial_port.o"
	@echo "... src/serial_port.i"
	@echo "... src/serial_port.s"
	@echo "... src/tower.o"
	@echo "... src/tower.i"
	@echo "... src/tower.s"
	@echo "... src/yolo.o"
	@echo "... src/yolo.i"
	@echo "... src/yolo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

